env:
  browser: true
  es2021: true
extends:
  - "plugin:react/recommended"
  - airbnb
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - prettier
rules:
  "react/jsx-filename-extension": [1, { "extensions": [".tsx", ".ts"] }]
  "import/extensions":
    - "error"
    - "ignorePackages"
    - { "js": "never", "jsx": "never", "ts": "never", "tsx": "never" }
  "no-use-before-define": "off"
  "jsx-a11y/no-autofocus": "warn"
settings:
  import/resolver:
    typescript: {}
